domain_site_settings: null
_core:
  default_config_hash: tkmglv8nLQzpf1cBcgSWFvPzgDJEfiz6bifpEQYXq84
etherealmatters_org:
  site_name: 'Ethereal Matters'
  site_slogan: ''
  site_mail: info@ecosleuth.com
  site_frontpage: /node/467
  site_403: ''
  site_404: ''
structuredatom_com:
  site_name: 'Ethereal Matters'
  site_slogan: ''
  site_mail: info@ecosleuth.com
  site_frontpage: /node/767
  site_403: ''
  site_404: ''
