account: UA-114595792-1
premium: 0
domain_mode: '0'
cross_domains: ''
visibility:
  request_path_mode: '0'
  request_path_pages: "/admin\r\n/admin/*\r\n/batch\r\n/node/add*\r\n/node/*/*\r\n/user/*/*"
  user_role_mode: '0'
  user_role_roles: {  }
  user_account_mode: '0'
track:
  outbound: 1
  mailto: 1
  files: 1
  files_extensions: '7z|aac|arc|arj|asf|asx|avi|bin|csv|doc(x|m)?|dot(x|m)?|exe|flv|gif|gz|gzip|hqx|jar|jpe?g|js|mp(2|3|4|e?g)|mov(ie)?|msi|msp|pdf|phps|png|ppt(x|m)?|pot(x|m)?|pps(x|m)?|ppam|sld(x|m)?|thmx|qtm?|ra(m|r)?|sea|sit|tar|tgz|torrent|txt|wav|wma|wmv|wpd|xls(x|m|b)?|xlt(x|m)|xlam|xml|z|zip'
  colorbox: true
  linkid: 0
  urlfragments: 0
  userid: 0
  messages: {  }
  site_search: false
  adsense: 0
  displayfeatures: 0
privacy:
  anonymizeip: 1
custom:
  dimension: {  }
  metric: {  }
codesnippet:
  create: {  }
  before: ''
  after: ''
translation_set: false
cache: 0
debug: 0
_core:
  default_config_hash: SMk3vOyh4KT6rXnqkDcNQ51YGpJzRV5hyig5SSIfU6U
