unprotected_forms:
  - user_login_form
  - search_form
  - search_block_form
  - views_exposed_form
  - honeypot_settings_form
protect_all_forms: false
log: true
element_name: email
time_limit: 3
expire: 300
form_settings:
  user_register_form: true
  user_pass: true
  contact_message_personal_form: true
  contact_message_sitewide_form: true
  node_article_form: false
  node_atom_form: false
  node_atomizer_form: false
  node_birkeland_form: false
  node_book_form: false
  node_element_form: false
  node_email_form: false
  node_event_form: false
  node_glossary_form: false
  node_landing_page_form: false
  node_news_form: false
  node_nuclet_binding_energies_form: false
  node_page_form: false
  node_snippet_form: false
  node_ticket_form: false
  comment_content_comment_form: true
  comment_taxonomy_comment_form: true
_core:
  default_config_hash: 9bVDfWSa_In6VzTXmy04jJ_3ZQobihKjO9isuuUCPaw
