content_roles:
  creator:
    enabled: false
    label: '? creator'
    permissions:
      - 'create ? content'
      - 'edit own ? content'
      - 'view ? revisions'
      - 'view own unpublished content'
      - 'create url aliases'
      - 'access in-place editing'
      - 'access contextual links'
      - 'access toolbar'
      - 'access panels in-place editing'
      - 'change layouts in place editing'
      - 'administer panelizer node ? content'
      - 'administer panelizer node ? layout'
      - 'use text format rich_text'
      - 'access media_browser entity browser pages'
      - 'view any unpublished content'
      - 'use draft_draft transition'
      - 'use draft_needs_review transition'
      - 'use needs_review_needs_review transition'
      - 'view latest version'
      - 'access image_browser entity browser pages'
      - 'use moderation sidebar'
  reviewer:
    enabled: false
    label: '? reviewer'
    permissions:
      - 'access content overview'
      - 'edit any ? content'
      - 'delete any ? content'
      - 'use draft_published transition'
      - 'use needs_review_draft transition'
      - 'use needs_review_published transition'
      - 'use published_published transition'
      - 'use published_archived transition'
      - 'view moderation states'
      - 'view any unpublished content'
      - 'view latest version'
      - 'access toolbar'
      - 'use moderation sidebar'
_core:
  default_config_hash: s0DQ96S4Q7lvAlNnSv52u3vDsYFN1OSBlqyVP1fd9WA
