features:
  node_user_picture: true
  comment_user_picture: true
  comment_user_verification: 1
  favicon: 1
logo:
  use_default: 0
  path: profiles/contrib/lightning/lightning.png
favicon:
  use_default: 0
  path: 'public://Deuterium_4_3.ico'
  mimetype: image/vnd.microsoft.icon
